"""Menu registry — the full MENU_REGISTRY item-definition tree.

The registry is a nested dict of menu/submenu item definitions (label / command /
tooltip / toggle / condition / submenu / type); separators are the string "---".
Command/label/condition lambdas call the collaborating _app_scripts modules
directly (imported below).
"""

import webbrowser
import pyperclip
from core.game_state import state

# Direct sibling imports (registry command/condition lambdas call these).
import _app_scripts.file.app_close as app_close
import _app_scripts.toggles.audio_toggles as audio_toggles
import _app_scripts.toggles.autoplay as autoplay_toggles
import _app_scripts.playback.blind_screen as blind_screen
import _app_scripts.bonus.bonus as bonus
from _app_scripts.bonus import answers as bonus_answers
from _app_scripts.bonus import buzz
import _app_scripts.toggles.censors as censors
import _app_scripts.playback.coming_up_ui as coming_up_ui
import _app_scripts.directory.scan as directory_scan
import _app_scripts.playback.dock_player as dock_player_mod
import _app_scripts.queue_round.lightning_rounds.edge_overlay as edge_overlay
import _app_scripts.queue_round.lightning_rounds.filter_overlay as filter_overlay
import _app_scripts.queue_round.fixed_lightning as fixed_lightning
import _app_scripts.queue_round.fixed_lightning_actions as fixed_lightning_actions
import _app_scripts.queue_round.lightning_rounds.grow_overlay as grow_overlay
import _app_scripts.information.information_popup as information_popup
import _app_scripts.queue_round.lightning_rounds.lightning_manager as lightning_manager
import _app_scripts.queue_round.lightning_rounds.lightning_settings as lightning_settings
import _app_scripts.ui.lists as lists
import _app_scripts.ui.menu_builder as menu_builder
import _app_scripts.file.metadata.metadata_display as metadata_display
import _app_scripts.file.metadata.metadata_fetch as metadata_fetch
import _app_scripts.queue_round.lightning_rounds.peek_dispatch as peek_dispatch
import _app_scripts.queue_round.lightning_rounds.peek_overlay as peek_overlay
import _app_scripts.theme.marks as playlist_marks
import _app_scripts.playlists.playlist as playlist_ops
import _app_scripts.playlists.infinite as infinite
import _app_scripts.playlists.filters as filters
import _app_scripts.playlists.playlist_io as playlist_io
import _app_scripts.theme.media_ops as media_ops
import _app_scripts.playlists.playlist_sources as playlist_sources
import _app_scripts.popout.popout_window as popout_window
import _app_scripts.playback.progress_bar as progress_bar_ops
import _app_scripts.file.scoreboard_control as scoreboard_control
import _app_scripts.search.search as search_ops
from _app_scripts.file import session_end
import _app_scripts.file.session_stats as session_stats
import _app_scripts.file.settings_actions as settings_actions
import _app_scripts.file.settings_popup as settings_popup
import _app_scripts.toggles.shortcut_actions as shortcut_actions
from _app_scripts.toggles import shortcut_dispatch
import _app_scripts.toggles.shortcut_editor as shortcut_editor
import _app_scripts.directory.stats as stats_ops
import _app_scripts.playback.streaming as streaming
import _app_scripts.queue_round.lightning_rounds.trivia_round as trivia_round
import _app_scripts.file.tutorial as tutorial
import _app_scripts.data.updates_io as updates_io
import _app_scripts.file.web_server.web_server as web_server
import _app_scripts.queue_round.youtube.youtube_editor as youtube_editor
import _app_scripts.queue_round.youtube.youtube_ui as youtube_ui
import _app_scripts.playback.ffmpeg_check as ffmpeg_check
import _app_scripts.playback.transport as transport

STREAM_ICON = '📶'

def get_menu_registry():
    return {

    # ── DIRECTORY ────────────────────────────────────────────────────────────
    "directory": [
        {"id": "dir_by_artist", "icon": "🎤", "label": "Themes by Artist",
         "tooltip": "List all themes grouped by artist.",
         "submenu": [
             {"id": "dir_by_artist_alpha", "label": "Alphabetical",  "command": lambda: stats_ops.show_artist_stats('alpha'), "tooltip": "Sort artists alphabetically."},
             {"id": "dir_by_artist_count", "label": "Theme Total",   "command": lambda: stats_ops.show_artist_stats('count'), "tooltip": "Sort artists by number of themes (most first)."},
         ]},
        {"id": "dir_by_playlist", "icon": "🎵", "label": "Themes by Playlist",
         "tooltip": "Browse themes inside your playlists.",
         "submenu": [
             {"id": "dir_by_playlist_user",   "label": "User Playlists",   "command": stats_ops.show_user_playlists,   "tooltip": "List your own playlists, then drill into a playlist's themes."},
             {"id": "dir_by_playlist_system", "label": "System Playlists", "command": stats_ops.show_system_playlists, "tooltip": "List the built-in system playlists, then drill into a playlist's themes."},
         ]},
        {"id": "dir_by_season", "icon": "🌸", "label": "Themes by Season",
         "command": stats_ops.show_season_stats, "tooltip": "List all themes grouped by season."},
        {"id": "dir_by_series", "icon": "📚", "label": "Themes by Series",
         "tooltip": "List all themes grouped by series.",
         "submenu": [
             {"id": "dir_by_series_alpha",      "label": "Alphabetical",  "command": lambda: stats_ops.show_series_stats('alpha'),      "tooltip": "Sort series alphabetically."},
             {"id": "dir_by_series_popularity", "label": "Popularity",    "command": lambda: stats_ops.show_series_stats('popularity'), "tooltip": "Sort series by MAL popularity rank (most popular first)."},
             {"id": "dir_by_series_count",      "label": "Theme Total",   "command": lambda: stats_ops.show_series_stats('count'),      "tooltip": "Sort series by number of themes (most first)."},
         ]},
        {"id": "dir_by_slug",   "icon": "🔑", "label": "Themes by Slug",
         "tooltip": "List all themes grouped by slug (OP1, ED2, etc.).",
         "submenu": [
             {"id": "dir_by_slug_alpha", "label": "Alphabetical",  "command": lambda: stats_ops.show_slug_stats('alpha'), "tooltip": "Sort slugs alphabetically."},
             {"id": "dir_by_slug_count", "label": "Theme Total",   "command": lambda: stats_ops.show_slug_stats('count'), "tooltip": "Sort slugs by number of themes (most first)."},
         ]},
        {"id": "dir_by_studio", "icon": "🏢", "label": "Themes by Studio",
         "tooltip": "List all themes grouped by studio.",
         "submenu": [
             {"id": "dir_by_studio_alpha", "label": "Alphabetical",  "command": lambda: stats_ops.show_studio_stats('alpha'), "tooltip": "Sort studios alphabetically."},
             {"id": "dir_by_studio_count", "label": "Theme Total",   "command": lambda: stats_ops.show_studio_stats('count'), "tooltip": "Sort studios by number of themes (most first)."},
         ]},
        {"id": "dir_by_tag",    "icon": "🏷",  "label": "Themes by Tag (MAL)",
         "tooltip": "List all themes grouped by MAL tag.",
         "submenu": [
             {"id": "dir_by_tag_alpha", "label": "Alphabetical",  "command": lambda: stats_ops.show_tag_stats('alpha'), "tooltip": "Sort MAL tags alphabetically."},
             {"id": "dir_by_tag_count", "label": "Theme Total",   "command": lambda: stats_ops.show_tag_stats('count'), "tooltip": "Sort MAL tags by number of themes (most first)."},
         ]},
        {"id": "dir_by_anilist_tag", "icon": "🔖", "label": "Themes by Tag (AniList)",
         "tooltip": "List all themes grouped by AniList tag.",
         "submenu": [
             {"id": "dir_by_anilist_tag_alpha", "label": "Alphabetical",  "command": lambda: stats_ops.show_anilist_tag_stats('alpha'), "tooltip": "Sort AniList tags alphabetically."},
             {"id": "dir_by_anilist_tag_count", "label": "Theme Total",   "command": lambda: stats_ops.show_anilist_tag_stats('count'), "tooltip": "Sort AniList tags by number of themes (most first)."},
         ]},
        {"id": "dir_by_title", "icon": "🎬", "label": "Themes by Title",
         "tooltip": "List all themes grouped by anime title (seasons listed separately).",
         "submenu": [
             {"id": "dir_by_title_alpha",      "label": "Alphabetical",  "command": lambda: stats_ops.show_title_stats('alpha'),      "tooltip": "Sort titles alphabetically."},
             {"id": "dir_by_title_popularity", "label": "Popularity",    "command": lambda: stats_ops.show_title_stats('popularity'), "tooltip": "Sort titles by MAL popularity rank (most popular first)."},
         ]},
        {"id": "dir_by_type",   "icon": "📺", "label": "Themes by Type",
         "command": stats_ops.show_type_stats,   "tooltip": "List all themes grouped by format/type."},
        {"id": "dir_by_year",   "icon": "📅", "label": "Themes by Year",
         "command": stats_ops.show_year_stats,   "tooltip": "List all themes grouped by year."},
    ],

    # ── FILE ────────────────────────────────────────────────────────────────
    "file": [
        {"id": "choose_directory", "icon": "📁", "label": "Choose Theme Directory",
         "button_label": "DIRECTORY", "command": directory_scan.select_directory,
         "tooltip": ("Choose the folder where your anime themes are stored.\n\n"
                     "The app expects files from AnimeThemes (torrent or downloaded).\n"
                     "It searches subfolders, so pick the top-level folder.\n\n"
                     "Custom files must be labeled as:\n"
                     "AnimeName-OP1-[MAL]49618[ART]Minami[SNG]Rude Lose Dance.webm")},
        "---",
        {"label": "Import", "icon": "►", "tooltip": "Import metadata or censors from GitHub.",
         "submenu": [
             {"id": "import_data", "label": "Import Data (from GitHub)",
              "button_label": "IMPORT DATA", "command": updates_io.import_data_from_source,
              "tooltip": "Imports metadata from a remote GitHub.\nDownloads a zip package and merges all metadata with your existing data."},
             {"id": "import_censors", "label": "Import Censors (Ramun's)",
              "button_label": "IMPORT CENSORS", "command": updates_io.import_censors,
              "tooltip": "Downloads and imports Ramun's censors from GitHub.\nSaved as 'ramuns_censors.json' in your files folder."},
         ]},
        {"id": "export_data", "icon": "📤", "label": "Export Data",
         "button_label": "EXPORT", "command": updates_io.export_metadata_package,
         "tooltip": "Exports all metadata files into a zip package for backup or sharing."},
        "---",
        {"id": "fetch_all_metadata", "icon": "❓", "label": "Fetch All Missing Metadata",
         "button_label": "FETCH ALL", "command": metadata_fetch.fetch_all_metadata,
         "tooltip": "Check all files in the directory for missing metadata and fetch any that are absent."},
        {"label": "Refresh Metadata", "icon": "⭮",
         "tooltip": "Refresh metadata from external sources.",
         "submenu": [
             {"id": "refresh_jikan", "icon": "⭮", "label": "Refresh Jikan (MAL)",
              "button_label": "REFRESH JIKAN", "command": metadata_fetch.refresh_all_metadata,
              "tooltip": "Refresh Jikan (MAL) metadata — score and members — for files in your directory."},
             {"id": "refresh_anilist", "icon": "A", "label": "Refresh AniList",
              "button_label": "REFRESH ANILIST", "command": metadata_fetch.refresh_all_anilist_metadata,
              "tooltip": "Refresh AniList metadata — scores, rankings, tags, characters — for files in your directory."},
             {"id": "refresh_igdb", "icon": "🎮", "label": "Refresh IGDB",
              "button_label": "REFRESH IGDB", "command": metadata_fetch.refresh_all_igdb_metadata,
              "tooltip": "Refresh IGDB metadata for game files in your directory."},
         ]},
        "---",
        {"icon": "🌐",
            "label": lambda: "Stop Web Server" if web_server.is_running() else "Start Web Server",
            "command": bonus_answers.toggle_web_server,
            "toggle": lambda: web_server.is_running(),
            "condition": lambda: web_server.NGROK_AVAILABLE or web_server.CLOUDFLARED_AVAILABLE,
            "tooltip": "Start or stop the web answer server that lets players submit bonus answers from their browser."
        },
        {"id": "open_scoreboard",  "icon": "▶", "label": "Open Scoreboard",
        "command": scoreboard_control.open_scoreboard,
        "condition": lambda: scoreboard_control.AVAILABLE and not scoreboard_control.is_running(),
        "tooltip": "Launch the scoreboard."},
        {"id": "close_scoreboard", "icon": "✕", "label": "Close Scoreboard",
        "command": lambda: scoreboard_control.send_command("quit"),
        "condition": lambda: scoreboard_control.is_running(),
        "tooltip": "Send a quit command to the running scoreboard."},
        {"id": "download_scoreboard", "icon": "⬇", "label": "Download Scoreboard",
        "command": updates_io.download_scoreboard,
        "condition": lambda: not scoreboard_control.AVAILABLE,
        "tooltip": "Download the Universal Scoreboard — a companion overlay for tracking scores during sessions."},
        {"id": "update_scoreboard", "icon": "🔄", "label": "Update Scoreboard",
        "command": lambda: scoreboard_control.send_command("check_update"),
        "condition": lambda: scoreboard_control.is_running(),
        "tooltip": "Ask the running scoreboard to check for and install a newer version."},
        {"label": "Scoreboard Actions", "icon": "⚙️",
        "condition": lambda: scoreboard_control.is_running(),
        "tooltip": "Control the scoreboard window.",
        "submenu": [
            {"id": "scoreboard_toggle",  "icon": "👁",  "label": "Toggle Visibility",
            "command": lambda: scoreboard_control.send_command("toggle"),
            "tooltip": "Show or hide the scoreboard."},
            {"id": "scoreboard_align",   "icon": "⇄",  "label": "Flip Alignment",
            "command": lambda: scoreboard_control.send_command("align"),
            "tooltip": "Toggle scoreboard between left and right alignment."},
            "---",
            {"id": "scoreboard_extend",  "icon": "▤",   "label": "Toggle Extended Stats",
            "command": lambda: scoreboard_control.send_command("extend"),
            "tooltip": "Toggle the extended statistics view."},
            "---",
            {"id": "scoreboard_grow",    "icon": "△",  "label": "Grow",
            "command": lambda: scoreboard_control.send_command("grow"),
            "tooltip": "Increase the scoreboard size."},
            {"id": "scoreboard_shrink",  "icon": "▽",  "label": "Shrink",
            "command": lambda: scoreboard_control.send_command("shrink"),
            "tooltip": "Decrease the scoreboard size."},
        ]},
        "---",
        {"id": "reset_session", "icon": "🗑",
         "label": lambda: f"Reset Session History [{session_stats.get_themes_played_count()}]",
         "button_label": "RESET SESSION", "command": session_stats.reset_session_history,
         "tooltip": "Clear the current session history.\nStarts a fresh session from this point."},
        "---",
        {"id": "settings", "icon": "⚙️", "label": "Configuration Settings",
         "button_label": "SETTINGS", "command": settings_popup.show_settings_popup,
         "tooltip": "Open settings to configure volume, colors, API keys, scaling, and more."},
        "---",
        {"id": "help", "icon": "❓", "label": "Help & Tutorial",
         "button_label": "HELP",
         "command": tutorial.open_tutorial_popup,
         "tooltip": "Open the Help & Tutorial window with a step-by-step guide to using the app."},
        {"id": "github", "icon": "🔗", "label": "View on GitHub",
         "button_label": "GITHUB",
         "command": lambda: webbrowser.open("https://github.com/ualkotob/guess-the-anime-playlist-tool"),
         "tooltip": "Open the GitHub repository for this app in your browser."},
        "---",
        {"id": "exit", "icon": "✕", "label": "Exit",
         "button_label": "EXIT", "command": app_close.on_app_close,
         "tooltip": "Close the application."},
    ],

    # ── PLAYLIST ────────────────────────────────────────────────────────────
    "playlist": [
        {"label": "Create Playlist", "icon": "➕",
         "submenu": [
             {"id": "create_infinite", "icon": "∞", "label": "Infinite",
              "button_label": "INFINITE",
              "tooltip": ("Creates a playlist that automatically adds new tracks as you reach the end"
                          " balancing popularity and season groups. Can be configured heavily.\n\n"
                          "This is the recommended playlist to use."),
              "submenu": [
                  {"id": "create_infinite_local", "label": "Local Files Only",
                   "command": lambda: playlist_ops.create_infinite_playlist(include_non_local=False),
                   "tooltip": "Create an infinite playlist using only files present in your local directory."},
                  {"id": "create_infinite_stream", "icon": STREAM_ICON, "label": "Include Streaming Themes",
                   "command": lambda: playlist_ops.create_infinite_playlist(include_non_local=True),
                   "tooltip": "Include non-local themes that will be streamed from AnimeThemes."},
              ]},
             "---",
             {"id": "create_standard", "label": "Standard (all files)",
              "button_label": "CREATE",
              "tooltip": ("Creates a playlist using all videos found in the directory.\n\n"
                          "Not recommended unless you have a curated local list of themes."),
              "submenu": [
                  {"id": "create_standard_local", "label": "Local Files Only",
                   "command": lambda: playlist_ops.generate_playlist_button(include_non_local=False),
                   "tooltip": "Create a playlist using only files present in your local directory."},
                  {"id": "create_standard_stream", "icon": STREAM_ICON, "label": "Include Streaming Themes",
                   "command": lambda: playlist_ops.generate_playlist_button(include_non_local=True),
                   "tooltip": "Include non-local themes from metadata that will be streamed from AnimeThemes."},
              ]},
             {"id": "create_anilist", "label": "From AniList ID",
              "button_label": "ANILIST",
              "tooltip": "Creates a playlist from an AniList user's anime list.",
              "submenu": [
                  {"id": "create_anilist_local", "label": "Local Files Only",
                   "command": lambda: playlist_sources.generate_anilist_playlist(include_non_local=False),
                   "tooltip": "Match only themes that are stored locally in your directory."},
                  {"id": "create_anilist_stream", "icon": STREAM_ICON, "label": "Include Streaming Themes",
                   "command": lambda: playlist_sources.generate_anilist_playlist(include_non_local=True),
                   "tooltip": "Include non-local themes from metadata that will be streamed from AnimeThemes."},
              ]},
             {"id": "create_animethemes", "label": "From AnimeThemes Playlist",
              "button_label": "ANIMETHEMES",
              "tooltip": ("Creates a playlist from an AnimeThemes playlist hashid.\n"
                          "URL format: https://animethemes.moe/playlist/hashid"),
              "submenu": [
                  {"id": "create_animethemes_local", "label": "Local Files Only",
                   "command": lambda: playlist_sources.generate_animethemes_playlist(include_non_local=False),
                   "tooltip": "Match only themes that are stored locally in your directory."},
                  {"id": "create_animethemes_stream", "icon": STREAM_ICON, "label": "Include Streaming Themes",
                   "command": lambda: playlist_sources.generate_animethemes_playlist(include_non_local=True),
                   "tooltip": "Include non-local themes from metadata that will be streamed from AnimeThemes."},
              ]},
             {"id": "create_session_log", "label": "From Session Log",
              "button_label": "SESSION LOG",
              "tooltip": ("Creates a playlist by matching themes from a saved session log file.\n\n"
                          "Session .txt files are stored in the sessions/ folder.\n"
                          "Themes are matched against your local files/metadata using title and slug."),
              "command": playlist_sources.generate_session_log_playlist},
             "---",
             {"id": "empty_playlist", "label": "Empty Playlist",
              "button_label": "EMPTY", "command": playlist_ops.empty_playlist,
              "tooltip": "Creates an empty playlist."},
         ]},
        "---",
        {"id": "view_playlist", "icon": "👁", "label": "View Playlist",
         "button_label": "PLAYLIST", "shortcut": True, "command": lists.show_playlist,
         "tooltip": ("List all themes in the playlist. Scrolls to the current index.\n"
                     "Select a theme to jump to it immediately.")},
        {"id": "go_to_index", "icon": "→", "label": "Go to Index",
         "command": transport.go_to_index,
         "condition": lambda: not state.metadata.playlist.get("infinite", False),
         "tooltip": "Jump to a specific track number in the playlist."},
        {"id": "remove_theme", "icon": "➖", "label": "Remove Theme",
         "button_label": "REMOVE", "command": lists.remove,
         "tooltip": ("Remove a theme from the playlist.\n\n"
                     "There is a confirmation dialogue after selecting.")},
        "---",
        {"id": "save_playlist", "label": "Save Playlist",
         "button_label": "SAVE", "command": playlist_io.save,
         "tooltip": ("Save the current playlist to its existing file in the playlists/ folder.\n\n"
                     "The current index is also saved so you can resume where you left off.")},
        {"id": "save_playlist_as", "label": "Save Playlist As",
         "button_label": "SAVE AS", "command": playlist_io.save_as,
         "tooltip": ("Save the current playlist under a new name.\n\n"
                     "You will be prompted for a name. Entering an existing name will overwrite it.\n"
                     "The current index is also saved so you can resume where you left off.")},
        {"id": "load_playlist", "label": "Load Playlist",
         "button_label": "LOAD", "command": playlist_io.load,
         "tooltip": ("Load a saved playlist.\n\n"
                     "Won't interrupt the currently playing theme.")},
        {"id": "load_system_playlist", "icon": "📋", "label": "Load System Playlist",
         "button_label": "SYSTEM LIST", "command": playlist_io.load_system_playlist,
         "tooltip": "Load a system playlist: Tagged, Favorite, Blind, Reveal, Mute Reveal, New, or Missing Artists."},
        {"id": "merge_playlist", "icon": "➕", "label": "Merge Playlist",
         "button_label": "MERGE", "command": playlist_io.merge_playlist,
         "condition": lambda: not state.metadata.playlist.get("infinite", False),
         "tooltip": ("Merge another playlist into the current one.\n"
                     "Only non-infinite playlists are listed. Duplicates are skipped.")},
        {"id": "delete_playlist", "icon": "❌", "label": "Delete a Playlist",
         "button_label": "DELETE", "command": playlist_io.delete,
         "tooltip": "Select a playlist from the list to delete. You will be asked to confirm."},
        "---",
        {"label": "Filter Playlist", "icon": "",
         "submenu": [
             {"id": "filter_editor", "label": "Open Filter Editor",
              "button_label": "FILTER", "command": filters.filters,
              "tooltip": ("Open a window to create, apply, and save playlist filters.")},
             {"id": "load_filter", "icon": "💾", "label": "Load Saved Filter",
              "button_label": "LOAD FILTER", "command": filters.load_filters,
              "tooltip": "Apply a previously saved filter to the current playlist."},
             {"id": "delete_filter", "icon": "❌", "label": "Delete Saved Filter",
              "button_label": "DEL FILTER", "command": filters.delete_filters,
              "tooltip": "Delete a saved filter. You will be asked to confirm."},
         ]},
        "---",
        {"label": "Sort Playlist", "icon": "🔀",
         "condition": lambda: not state.metadata.playlist.get("infinite", False),
         "tooltip": "Sort the playlist by field and direction.",
         "submenu": [
             {"label": "Filename",
              "tooltip": "Sort by the theme's filename.",
              "submenu": [
                  {"id": "sort_filename_asc",  "label": "Ascending ↑",  "command": lambda: playlist_ops.sort_playlist(0),
                   "tooltip": "Sort filenames A → Z."},
                  {"id": "sort_filename_desc", "label": "Descending ↓", "command": lambda: playlist_ops.sort_playlist(1),
                   "tooltip": "Sort filenames Z → A."},
              ]},
             {"label": "Title",
              "tooltip": "Sort by the anime's Japanese title.",
              "submenu": [
                  {"id": "sort_title_asc",  "label": "Ascending ↑",  "command": lambda: playlist_ops.sort_playlist(2),
                   "tooltip": "Sort titles A → Z."},
                  {"id": "sort_title_desc", "label": "Descending ↓", "command": lambda: playlist_ops.sort_playlist(3),
                   "tooltip": "Sort titles Z → A."},
              ]},
             {"label": "English Title",
              "tooltip": "Sort by the anime's English title.",
              "submenu": [
                  {"id": "sort_eng_title_asc",  "label": "Ascending ↑",  "command": lambda: playlist_ops.sort_playlist(4),
                   "tooltip": "Sort English titles A → Z."},
                  {"id": "sort_eng_title_desc", "label": "Descending ↓", "command": lambda: playlist_ops.sort_playlist(5),
                   "tooltip": "Sort English titles Z → A."},
              ]},
             {"label": "Score",
              "tooltip": "Sort by MAL score.",
              "submenu": [
                  {"id": "sort_score_asc",  "label": "Ascending ↑",  "command": lambda: playlist_ops.sort_playlist(6),
                   "tooltip": "Sort lowest score first."},
                  {"id": "sort_score_desc", "label": "Descending ↓", "command": lambda: playlist_ops.sort_playlist(7),
                   "tooltip": "Sort highest score first."},
              ]},
             {"label": "Members",
              "tooltip": "Sort by MAL member count (popularity).",
              "submenu": [
                  {"id": "sort_members_asc",  "label": "Ascending ↑",  "command": lambda: playlist_ops.sort_playlist(8),
                   "tooltip": "Sort least popular first."},
                  {"id": "sort_members_desc", "label": "Descending ↓", "command": lambda: playlist_ops.sort_playlist(9),
                   "tooltip": "Sort most popular first."},
              ]},
             {"label": "Season",
              "tooltip": "Sort by the anime's airing season and year.",
              "submenu": [
                  {"id": "sort_season_asc",  "label": "Ascending ↑",  "command": lambda: playlist_ops.sort_playlist(10),
                   "tooltip": "Sort oldest season first."},
                  {"id": "sort_season_desc", "label": "Descending ↓", "command": lambda: playlist_ops.sort_playlist(11),
                   "tooltip": "Sort newest season first."},
              ]},
         ]},
        {"label": "Shuffle Playlist", "icon": "🔀",
         "condition": lambda: not state.metadata.playlist.get("infinite", False),
         "submenu": [
             {"id": "shuffle_playlist", "label": "Random",
              "button_label": "SHUFFLE", "command": playlist_ops.randomize_playlist,
              "tooltip": "Completely random shuffle of the current playlist."},
             {"id": "weighted_shuffle", "icon": "⚖️", "label": "Weighted",
              "button_label": "W.SHUFFLE", "command": playlist_ops.weighted_randomize,
              "tooltip": ("Weighted shuffle balancing popular/niche and old/new anime, "
                          "while avoiding the same series appearing too close together.\n"
                          "Ideal for trivia sessions.")},
         ]},
        {"type": "radiogroup",
         "condition": lambda: state.metadata.playlist.get("infinite", False),
         "options": state.playlist_ui.difficulty_options,
         "variable": lambda: state.metadata.playlist.get("difficulty", 2),
         "command": infinite._set_difficulty_from_menu},
        {"id": "infinite_settings", "icon": "🛠", "label": "Infinite Settings",
         "button_label": "INF. SETTINGS", "command": settings_actions.open_infinite_settings_editor,
         "condition": lambda: state.metadata.playlist.get("infinite", False),
         "tooltip": "Open the Infinite Settings editor to configure infinite playlist behavior."},
        "---",
        {"label": "Bulk Mark Playlist", "icon": "►",
         "tooltip": "Apply or remove a mark for every theme in the current playlist.",
         "submenu": [
             {"id": "bulk_tag",           "icon": "❌", "label": "Bulk Tag Playlist",
              "button_label": "BULK TAG",      "command": playlist_marks.bulk_tag_playlist,
              "tooltip": "Bulk tag or untag every theme in the current playlist. Requires confirmation."},
             {"id": "bulk_favorite",      "icon": "❤",  "label": "Bulk Favorite Playlist",
              "button_label": "BULK FAV",      "command": playlist_marks.bulk_favorite_playlist,
              "tooltip": "Bulk favorite or unfavorite every theme in the current playlist. Requires confirmation."},
             {"id": "bulk_blind_mark",    "icon": "👁", "label": "Bulk Blind Mark Playlist",
              "button_label": "BULK BLIND",    "command": playlist_marks.bulk_blind_mark_playlist,
              "tooltip": "Bulk blind-mark or unmark every theme. Mutually exclusive with Reveal/Mute Reveal. Requires confirmation."},
             {"id": "bulk_peek_mark",     "icon": "👀", "label": "Bulk Reveal Mark Playlist",
              "button_label": "BULK RV",        "command": playlist_marks.bulk_peek_mark_playlist,
              "tooltip": "Bulk reveal-mark or unmark every theme in the playlist. Mutually exclusive with Blind/Mute Reveal. Requires confirmation."},
             {"id": "bulk_mute_peek_mark","icon": "🔇", "label": "Bulk Mute Reveal Mark Playlist",
              "button_label": "BULK MUTE RV",   "command": playlist_marks.bulk_mute_peek_mark_playlist,
              "tooltip": "Bulk mute-reveal-mark or unmark every theme in the playlist. Mutually exclusive with Blind/Reveal. Requires confirmation."},
         ]},
    ],

    # ── QUEUE ────────────────────────────────────────────────────────────────
    "queue": [
        {"id": "queue_blind_round", "icon": "👁", "label": "Blind Round",
         "button_label": "BLIND NEXT", "shortcut": True, "command": blind_screen.toggle_blind_round,
         "toggle":  lambda: blind_screen.blind_round_toggle,
         "cycle_pos": ("cycle_blind_peek", 1),
         "tooltip": "Queue the next theme as a Blind Round — audio only, screen covered."},
        {"id": "queue_peek_round", "icon": "👀", "label": "Reveal Round",
         "button_label": "REVEAL NEXT", "shortcut": True, "command": peek_dispatch.toggle_peek_round,
         "toggle":  lambda: peek_dispatch.peek_round_toggle,
         "cycle_pos": ("cycle_blind_peek", 2),
         "tooltip": "Queue the next theme as a Reveal Round — visuals are partially obscured (blur, zoom, slice, etc.).",
         "submenu": [
             {"label": "Turn Off", "icon": "✖", "command": peek_dispatch.toggle_peek_round,
              "condition": lambda: peek_dispatch.peek_round_toggle},
             {"icon": "🔀", "label": "Random", "command": lambda: peek_dispatch._queue_peek_random(mute=False),
              "toggle": lambda: peek_dispatch.peek_round_toggle and peek_dispatch._queued_peek_variant[0] is None},
             "---",
             *[{"icon": icon, "label": label,
                "command": lambda v=v: peek_dispatch._queue_peek_variant(v, mute=False),
                "toggle": lambda v=v: peek_dispatch.peek_round_toggle and peek_dispatch._queued_peek_variant[0] == v,
                "tooltip": tooltip}
               for v, (icon, label, tooltip) in peek_dispatch._PEEK_VARIANT_LABELS.items()],
         ]},
        {"id": "queue_mute_peek_round", "icon": "🔇", "label": "Mute Reveal Round",
         "button_label": "MUTE RV NEXT", "shortcut": True, "command": peek_dispatch.toggle_mute_peek_round,
         "toggle":  lambda: peek_dispatch.mute_peek_round_toggle,
         "cycle_pos": ("cycle_blind_peek", 3),
         "tooltip": "Queue the next theme as a Mute Reveal Round — visuals partially obscured, audio muted.",
         "submenu": [
             {"label": "Turn Off", "icon": "✖", "command": peek_dispatch.toggle_mute_peek_round,
              "condition": lambda: peek_dispatch.mute_peek_round_toggle},
             {"icon": "🔀", "label": "Random", "command": lambda: peek_dispatch._queue_peek_random(mute=True),
              "toggle": lambda: peek_dispatch.mute_peek_round_toggle and peek_dispatch._queued_peek_variant[0] is None},
             "---",
             *[{"icon": icon, "label": label,
                "command": lambda v=v: peek_dispatch._queue_peek_variant(v, mute=True),
                "toggle": lambda v=v: peek_dispatch.mute_peek_round_toggle and peek_dispatch._queued_peek_variant[0] == v,
                "tooltip": tooltip}
               for v, (icon, label, tooltip) in peek_dispatch._PEEK_VARIANT_LABELS.items()],
         ]},
        "---",
        {"icon": "⚡", "label": "Lightning Rounds",
         "tooltip": "Start a lightning round of a chosen type.",
         "submenu": [
             {"id": f"lightning_{k}", "icon": v.get("icon", ""), "label": k.upper(),
              "button_label": k.upper(),
              "command": (lambda k=k: lightning_manager.toggle_light_mode(k)),
              "toggle":  lambda k=k: state.lightning.light_mode == k,
              "tooltip": v.get("desc", "")}
             for k, v in lightning_settings.light_modes.items()
         ]},
        {"id": "lightning_variety", "icon": "🎲", "label": "Variety Lightning Round",
         "button_label": "VARIETY", "shortcut": True, "command": lambda: lightning_manager.toggle_light_mode("variety"),
         "toggle":  lambda: state.lightning.light_mode == "variety",
         "tooltip": "Start a Variety Lightning Round — randomly picks round types weighted by popularity."},
        {"id": "lightning_settings", "icon": "🛠", "label": "Lightning Settings",
         "button_label": "LT.SETTINGS", "command": settings_actions.open_settings_editor,
         "tooltip": "Edit length, variants, and variety settings for each lightning round type."},
        "---",
        {"id": "show_youtube", "icon": "▶", "label": "YouTube Videos",
         "button_label": "YOUTUBE", "shortcut": True, "command": youtube_ui.show_youtube_playlist,
         "tooltip": "Browse and queue a YouTube video to play after the current theme."},
        {"id": "show_archived_youtube", "icon": "📦", "label": "Archived YouTube Videos",
         "button_label": "ARCHIVED YT", "command": youtube_ui.show_archived_youtube_playlist,
         "tooltip": "Browse and queue an archived YouTube video."},
        {"id": "manage_youtube", "icon": "🎥", "label": "Manage YouTube Videos",
         "button_label": "MANAGE YT", "command": youtube_editor.open_youtube_editor,
         "tooltip": "Add, edit, and archive YouTube videos for queuing."},
        "---",
        {"id": "show_fixed_lightning", "icon": "📋", "label": "Fixed Lightning Rounds",
         "button_label": "FIXED ROUND", "shortcut": True, "command": fixed_lightning_actions.show_fixed_lightning_list,
         "tooltip": "Queue up a curated fixed lightning round playlist."},
        {"id": "manage_fixed_rounds", "icon": "📋", "label": "Manage Fixed Lightning Rounds",
         "button_label": "MANAGE FIXED", "command": fixed_lightning.open_fixed_lightning_manager,
         "tooltip": "Create and manage curated fixed lightning round playlists."},
    ],

    # ── BONUS ─────────────────────────────────────────────────────────────────
    "bonus": [
        {"label": "Auto Bonus at Start", "icon": "🎲",
         "toggle": lambda: state.controls.auto_bonus_start is not None,
         "tooltip": "Automatically start a bonus question at the beginning of each theme.",
         "submenu": [
             {"icon": "✕", "label": "Off",              "command": lambda: bonus.set_auto_bonus_start(state.controls.auto_bonus_start), "condition": lambda: state.controls.auto_bonus_start is not None, "toggle": lambda: False, "tooltip": "Disable auto bonus at start."},
             "---",
             {"icon": "🎲", "label": "Random",          "command": lambda: bonus.set_auto_bonus_start("random"),     "toggle": lambda: state.controls.auto_bonus_start == "random",     "tooltip": "Pick a random bonus type each time."},
             "---",
             {"icon": "💬", "label": "Free Form",        "command": lambda: bonus.set_auto_bonus_start("freeform"),   "toggle": lambda: state.controls.auto_bonus_start == "freeform",   "condition": lambda: state.playback.bonus_settings.get("freeform", {}).get("show_in_menu", True), "tooltip": "Open a free-answer prompt."},
             {"icon": "🔔", "label": "Buzzer",        "command": lambda: bonus.set_auto_bonus_start("buzzer"),   "toggle": lambda: state.controls.auto_bonus_start == "buzzer",   "condition": lambda: state.playback.bonus_settings.get("buzzer", {}).get("show_in_menu", True), "tooltip": "Open a buzzer prompt."},
             "---",
             {"icon": "４", "label": "Multiple Choice",  "command": lambda: bonus.set_auto_bonus_start("multiple"),   "toggle": lambda: state.controls.auto_bonus_start == "multiple",   "condition": lambda: state.playback.bonus_settings.get("multiple", {}).get("show_in_menu", True), "tooltip": "Multiple-choice: guess the anime from 4 options."},
             {"icon": "📅", "label": "Year",             "command": lambda: bonus.set_auto_bonus_start("year"),       "toggle": lambda: state.controls.auto_bonus_start == "year",       "condition": lambda: state.playback.bonus_settings.get("year", {}).get("show_in_menu", True), "tooltip": "Guess the year this anime first aired."},
             {"icon": "🏆", "label": "Score",            "command": lambda: bonus.set_auto_bonus_start("score"),      "toggle": lambda: state.controls.auto_bonus_start == "score",      "condition": lambda: state.playback.bonus_settings.get("score", {}).get("show_in_menu", True), "tooltip": "Guess the MyAnimeList score (0.0–10.0)."},
             {"icon": "👥", "label": "Members",          "command": lambda: bonus.set_auto_bonus_start("members"),    "toggle": lambda: state.controls.auto_bonus_start == "members",    "condition": lambda: state.playback.bonus_settings.get("members", {}).get("show_in_menu", True), "tooltip": "Guess the number of MyAnimeList members."},
             {"icon": "🥇", "label": "Popularity Rank",  "command": lambda: bonus.set_auto_bonus_start("popularity"), "toggle": lambda: state.controls.auto_bonus_start == "popularity", "condition": lambda: state.playback.bonus_settings.get("popularity", {}).get("show_in_menu", True), "tooltip": "Guess the popularity rank on MyAnimeList."},
             {"icon": "🔖", "label": "Tags",             "command": lambda: bonus.set_auto_bonus_start("tags"),       "toggle": lambda: state.controls.auto_bonus_start == "tags",       "condition": lambda: state.playback.bonus_settings.get("tags", {}).get("show_in_menu", True), "tooltip": "Guess the genres/themes/demographics tags."},
             {"icon": "🏢", "label": "Studio",           "command": lambda: bonus.set_auto_bonus_start("studio"),     "toggle": lambda: state.controls.auto_bonus_start == "studio",     "condition": lambda: state.playback.bonus_settings.get("studio", {}).get("show_in_menu", True), "tooltip": "Guess the studio that made this anime."},
             {"icon": "🎤", "label": "Artist",           "command": lambda: bonus.set_auto_bonus_start("artist"),     "toggle": lambda: state.controls.auto_bonus_start == "artist",     "condition": lambda: state.playback.bonus_settings.get("artist", {}).get("show_in_menu", True), "tooltip": "Guess the artist who performed the theme."},
             {"icon": "🎵", "label": "Song Title",       "command": lambda: bonus.set_auto_bonus_start("song"),       "toggle": lambda: state.controls.auto_bonus_start == "song",       "condition": lambda: state.playback.bonus_settings.get("song", {}).get("show_in_menu", True), "tooltip": "Guess the name of the song."},
             {"icon": "👤", "label": "Characters",       "command": lambda: bonus.set_auto_bonus_start("characters"), "toggle": lambda: state.controls.auto_bonus_start == "characters", "condition": lambda: state.playback.bonus_settings.get("characters", {}).get("show_in_menu", True), "tooltip": "Pick the correct characters from the anime."},
         ]},
        "---",
        {"id": "bonus_freeform",  "icon": "💬", "label": "Free Form",          "button_label": "FREE FORM",  "shortcut": True, "command": lambda: bonus.guess_extra("freeform"),   "toggle": lambda: bonus.guessing_extra == "freeform",   "cycle_pos": ("cycle_guess_other", 1), "condition": lambda: state.playback.bonus_settings.get("freeform", {}).get("show_in_menu", True), "tooltip": "Open a free-answer prompt."},
        {"id": "bonus_buzzer",    "icon": "🔔", "label": "Buzzer",             "button_label": "BUZZER",     "shortcut": True, "command": lambda: bonus.guess_extra("buzzer"),     "toggle": lambda: bonus.guessing_extra == "buzzer",     "condition": lambda: web_server.is_running() and state.playback.bonus_settings.get("buzzer", {}).get("show_in_menu", True), "tooltip": "Open a buzzer-only web bonus round."},
        {"id": "buzzer_lock", "icon": "🔒", "label": "Lock", "button_label": "BUZZ LOCK",
        "command": buzz._web_buzzer_lock,
        "toggle": lambda: web_server.buzzer_is_locked(),
        "condition": lambda: web_server.is_running() and bonus.guessing_extra == "buzzer",
        "tooltip": "Toggle buzzer lock."},
        {"id": "buzzer_reset", "icon": "♻️", "label": "Reset", "button_label": "BUZZ RESET",
        "command": buzz._web_buzzer_reset,
        "condition": lambda: web_server.is_running() and bonus.guessing_extra == "buzzer",
        "tooltip": "Clear submitted buzzes without changing lock state."},
        "---",
        {"id": "bonus_multiple", "icon": "４", "label": "Multiple Choice",  "button_label": "MULTIPLE",  "shortcut": True, "command": lambda: bonus.guess_extra("multiple"),  "toggle": lambda: bonus.guessing_extra == "multiple",  "condition": lambda: state.playback.bonus_settings.get("multiple", {}).get("show_in_menu", True), "tooltip": "Multiple-choice: guess the anime from 4 options."},
        {"id": "bonus_year",     "icon": "📅", "label": "Year",              "button_label": "YEAR",       "shortcut": True, "command": lambda: bonus.guess_extra("year"),       "toggle": lambda: bonus.guessing_extra == "year",       "cycle_pos": ("cycle_guess_stats", 1), "condition": lambda: state.playback.bonus_settings.get("year", {}).get("show_in_menu", True), "tooltip": "Guess the year this anime first aired."},
        {"id": "bonus_score",    "icon": "🏆", "label": "Score",             "button_label": "SCORE",      "shortcut": True, "command": lambda: bonus.guess_extra("score"),      "toggle": lambda: bonus.guessing_extra == "score",      "cycle_pos": ("cycle_guess_stats", 2), "condition": lambda: state.playback.bonus_settings.get("score", {}).get("show_in_menu", True), "tooltip": "Guess the MyAnimeList score (0.0–10.0)."},
        {"id": "bonus_members",  "icon": "👥", "label": "Members",           "button_label": "MEMBERS",    "shortcut": True, "command": lambda: bonus.guess_extra("members"),    "toggle": lambda: bonus.guessing_extra == "members",    "cycle_pos": ("cycle_guess_stats", 4), "condition": lambda: state.playback.bonus_settings.get("members", {}).get("show_in_menu", True), "tooltip": "Guess the number of MyAnimeList members."},
        {"id": "bonus_rank",     "icon": "🥇", "label": "Popularity Rank",   "button_label": "RANK",       "shortcut": True, "command": lambda: bonus.guess_extra("popularity"), "toggle": lambda: bonus.guessing_extra == "popularity", "cycle_pos": ("cycle_guess_stats", 3), "condition": lambda: state.playback.bonus_settings.get("popularity", {}).get("show_in_menu", True), "tooltip": "Guess the popularity rank on MyAnimeList."},
        {"id": "bonus_tags",     "icon": "🔖", "label": "Tags",              "button_label": "TAGS",       "shortcut": True, "command": lambda: bonus.guess_extra("tags"),       "toggle": lambda: bonus.guessing_extra == "tags",       "condition": lambda: state.playback.bonus_settings.get("tags", {}).get("show_in_menu", True), "tooltip": "Guess the genres/themes/demographics tags."},
        {"id": "bonus_studio",   "icon": "🏢", "label": "Studio",            "button_label": "STUDIO",     "shortcut": True, "command": lambda: bonus.guess_extra("studio"),     "toggle": lambda: bonus.guessing_extra == "studio",     "cycle_pos": ("cycle_guess_other", 2), "condition": lambda: state.playback.bonus_settings.get("studio", {}).get("show_in_menu", True), "tooltip": "Guess the studio that made this anime."},
        {"id": "bonus_artist",   "icon": "🎤", "label": "Artist",            "button_label": "ARTIST",     "shortcut": True, "command": lambda: bonus.guess_extra("artist"),     "toggle": lambda: bonus.guessing_extra == "artist",     "cycle_pos": ("cycle_guess_other", 4), "condition": lambda: state.playback.bonus_settings.get("artist", {}).get("show_in_menu", True), "tooltip": "Guess the artist who performed the theme."},
        {"id": "bonus_song",     "icon": "🎵", "label": "Song Title",        "button_label": "SONG",       "shortcut": True, "command": lambda: bonus.guess_extra("song"),       "toggle": lambda: bonus.guessing_extra == "song",       "cycle_pos": ("cycle_guess_other", 3), "condition": lambda: state.playback.bonus_settings.get("song", {}).get("show_in_menu", True), "tooltip": "Guess the name of the song."},
        {"id": "bonus_chars",    "icon": "👤", "label": "Characters",        "button_label": "CHARACTERS", "shortcut": True, "command": lambda: bonus.guess_extra("characters"), "toggle": lambda: bonus.guessing_extra == "characters", "condition": lambda: state.playback.bonus_settings.get("characters", {}).get("show_in_menu", True), "tooltip": "Identify 2 characters from this anime out of 6 shown."},
        "---",
        {"label": "Bonus Settings", "icon": "⚙️", "button_label": "BONUS SETTINGS", "command": settings_actions.open_bonus_settings_editor, "tooltip": "Configure points, lightning points, and random eligibility for each bonus type."},
    ],

    # ── INFORMATION ───────────────────────────────────────────────────────────
    "information": [
        {"id": "info_popup", "icon": "ℹ", "label": "Info Popup",
         "button_label": "INFO", "shortcut": True, "command": information_popup.toggle_info_popup,
         "toggle":  lambda: information_popup.is_title_window_up() and not state.info_display.title_info_only,
         "tooltip": "Show or hide the information popup at the bottom of the screen."},
        {"id": "title_popup", "icon": "𝕋", "label": "Title Popup",
         "button_label": "TITLE", "shortcut": True, "command": information_popup.toggle_title_info_popup,
         "toggle":  lambda: information_popup.is_title_window_up() and state.info_display.title_info_only,
         "tooltip": "Show or hide the title popup at the bottom of the screen."},
        {"id": "artist_info", "icon": "🎤", "label": "Artist Info",
         "button_label": "ARTIST INFO", "shortcut": True, "command": information_popup.toggle_artist_info_popup,
         "toggle":  lambda: bool(state.info_display.artist_info_display),
         "tooltip": "Show or hide the info popup listing themes by this artist."},
        {"id": "studio_info", "icon": "🏢", "label": "Studio Info",
         "button_label": "STUDIO INFO", "shortcut": True, "command": information_popup.toggle_studio_info_popup,
         "toggle":  lambda: bool(state.info_display.studio_info_display),
         "tooltip": "Show or hide the info popup listing anime by this studio."},
        {"id": "season_rankings", "icon": "📅", "label": "Season Rankings",
         "button_label": "SEASON", "shortcut": True, "command": information_popup.toggle_season_info_popup,
         "toggle":  lambda: bool(state.info_display.season_info_display),
         "tooltip": "Show or hide the info popup with season popularity rankings."},
        {"id": "year_rankings", "icon": "🗓", "label": "Year Rankings",
         "button_label": "YEAR", "shortcut": True, "command": information_popup.toggle_year_info_popup,
         "toggle":  lambda: bool(state.info_display.year_info_display),
         "tooltip": "Show or hide the info popup with year popularity rankings."},
        "---",
        {"id": "auto_info_start", "icon": "⏪", "label": "Auto-show at Start",
         "button_label": "AUTO START", "shortcut": True, "command": information_popup.toggle_auto_info_start,
         "toggle":  lambda: state.controls.auto_info_start,
         "tooltip": "When enabled, automatically shows the info popup at the start of each theme."},
        {"id": "auto_info_end", "icon": "⏩", "label": "Auto-show at End",
         "button_label": "AUTO END", "shortcut": True, "command": information_popup.toggle_auto_info_end,
         "toggle":  lambda: state.controls.auto_info_end,
         "tooltip": "When enabled, automatically shows the info popup during the last 8 seconds."},
        "---",
        {"id": "end_session", "icon": "", "label": "End Screen",
         "button_label": "END SESSION", "shortcut": True, "command": session_end.end_session,
         "tooltip": "Display the end session screen with a scrolling message and themes played count."},
    ],

    # ── TOGGLE ───────────────────────────────────────────────────────────────
    "toggles": [
        {"id": "blind", "icon": "👁", "label": "Blind",
         "button_label": "BLIND",
         "shortcut": True, "command": lambda: blind_screen.blind(True),
         "toggle":  lambda: blind_screen.black_overlay is not None,
         "tooltip": "Covers the screen with a color matching the average screen color. Shows a progress bar if a video is playing."},
        {"id": "peek", "icon": "👀", "label": "Reveal",
         "button_label": "REVEAL",
         "shortcut": True, "command": peek_dispatch.toggle_peek,
         "toggle":  lambda: bool(peek_overlay.peek_overlay1 or edge_overlay.edge_overlay_box or grow_overlay.grow_overlay_boxes or filter_overlay.filter_vf_active),
         "submenu": [
             {"label": "Turn Off", "icon": "✖", "command": peek_dispatch.toggle_peek,
              "condition": lambda: bool(peek_overlay.peek_overlay1 or edge_overlay.edge_overlay_box or grow_overlay.grow_overlay_boxes or filter_overlay.filter_vf_active)},
             {"id": "peek_random",   "label": "Random",   "icon": "🔀", "shortcut": True, "command": lambda: peek_dispatch._activate_peek_variant(peek_dispatch.get_next_peek_mode()),
              "condition": lambda: not bool(peek_overlay.peek_overlay1 or edge_overlay.edge_overlay_box or grow_overlay.grow_overlay_boxes or filter_overlay.filter_vf_active)},
             {"type": "separator", "condition": lambda: not bool(peek_overlay.peek_overlay1 or edge_overlay.edge_overlay_box or grow_overlay.grow_overlay_boxes or filter_overlay.filter_vf_active)},
             {"id": "peek_blur",     "label": "Blur",     "icon": "🌫", "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if (filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'blur') else peek_dispatch._activate_peek_variant('blur'),
              "toggle": lambda: bool(filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'blur'),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("blur", True)},
             {"id": "peek_edge",     "label": "Edge",     "icon": "◼",  "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if edge_overlay.edge_overlay_box else peek_dispatch._activate_peek_variant('edge'),
              "toggle": lambda: bool(edge_overlay.edge_overlay_box),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("edge", True)},
             {"id": "peek_grow",     "label": "Grow",     "icon": "⬛", "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if grow_overlay.grow_overlay_boxes else peek_dispatch._activate_peek_variant('grow'),
              "toggle": lambda: bool(grow_overlay.grow_overlay_boxes),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("grow", True)},
             {"id": "peek_outline",   "label": "Outline",   "icon": "✏️",  "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if (filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'outline') else peek_dispatch._activate_peek_variant('outline'),
              "toggle": lambda: bool(filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'outline'),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("outline", True)},
             {"id": "peek_pixelize", "label": "Pixelize", "icon": "🟦", "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if (filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'pixelize') else peek_dispatch._activate_peek_variant('pixelize'),
              "toggle": lambda: bool(filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'pixelize'),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("pixelize", True)},
             {"id": "peek_slice",    "label": "Slice",    "icon": "◧",  "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if peek_overlay.peek_overlay1 else peek_dispatch._activate_peek_variant('slice'),
              "toggle": lambda: bool(peek_overlay.peek_overlay1),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("slice", True)},
             {"id": "peek_wave",     "label": "Wave",     "icon": "🌊", "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if (filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'wave') else peek_dispatch._activate_peek_variant('wave'),
              "toggle": lambda: bool(filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'wave'),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("wave", True)},
             {"id": "peek_zoom",     "label": "Zoom",     "icon": "🔍", "shortcut": True,
              "command": lambda: peek_dispatch.toggle_peek() if (filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'zoom') else peek_dispatch._activate_peek_variant('zoom'),
              "toggle": lambda: bool(filter_overlay.filter_vf_active and filter_overlay._filter_vf_variant == 'zoom'),
              "condition": lambda: state.playback.lightning_mode_settings.get("reveal",{}).get("show_in_menu",{}).get("zoom", True)},
         ],
         "tooltip": "When off: opens a submenu to pick a variant (or random). When on: turns off."},
        {"id": "narrow_peek", "icon": "◀", "label": "Reveal Less",
         "button_label": "RV LESS",
         "shortcut": True, "command": peek_dispatch.narrow_peek,
         "tooltip": "Reveals less — increases the obscuring effect."},
        {"id": "widen_peek", "icon": "▶", "label": "Reveal More",
         "button_label": "RV MORE",
         "shortcut": True, "command": peek_dispatch.widen_peek,
         "tooltip": "Reveals more — decreases the obscuring effect."},
        {"id": "mute", "icon": "🔇", "label": "Mute",
         "button_label": "MUTE",
         "shortcut": True, "command": audio_toggles.toggle_mute,
         "toggle":  lambda: state.controls.light_muted if (state.lightning.light_mode or state.lightning.light_round_started) else state.controls.disable_video_audio,
         "tooltip": "Toggles muting the video/theme audio."},
        {"id": "distort_audio", "icon": "🎚", "label": "Distort Audio",
         "button_label": "DISTORT",
         "toggle": lambda: bool(audio_toggles.audio_distortions_active),
         "tooltip": "Apply audio distortion filters to make themes harder to recognise.",
         "submenu": [
             {"id": "distort_echo",       "icon": "🔊", "label": "Echo",       "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("echo"),      "toggle": lambda: "echo"       in audio_toggles.audio_distortions_active, "tooltip": "Echo / reverb effect."},
             {"id": "distort_flanger",    "icon": "🌀", "label": "Flanger",    "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("flanger"),   "toggle": lambda: "flanger"    in audio_toggles.audio_distortions_active, "tooltip": "Swirling / wobbly flanger effect."},
             {"id": "distort_vibrato",    "icon": "🎵", "label": "Vibrato",    "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("vibrato"),   "toggle": lambda: "vibrato"    in audio_toggles.audio_distortions_active, "tooltip": "Pitch oscillation at 7 Hz."},
             {"id": "distort_telephone",  "icon": "📞", "label": "Telephone",  "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("telephone"), "toggle": lambda: "telephone"  in audio_toggles.audio_distortions_active, "tooltip": "Narrow phone-band filter (300–3400 Hz only)."},
             {"id": "distort_underwater", "icon": "🌊", "label": "Underwater", "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("underwater"),"toggle": lambda: "underwater" in audio_toggles.audio_distortions_active, "tooltip": "Heavy lowpass + reverb — muffled underwater effect."},
             {"id": "distort_chipmunk",   "icon": "🐿", "label": "Chipmunk",   "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("chipmunk"),  "toggle": lambda: "chipmunk"   in audio_toggles.audio_distortions_active, "tooltip": "2× pitch up — chipmunk voice."},
             {"id": "distort_demon",      "icon": "😈", "label": "Demon",      "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("demon"),     "toggle": lambda: "demon"      in audio_toggles.audio_distortions_active, "tooltip": "0.5× pitch down — deep demon voice."},
             {"id": "distort_vaporwave",  "icon": "🌸", "label": "Vaporwave",  "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("vaporwave"), "toggle": lambda: "vaporwave"  in audio_toggles.audio_distortions_active, "tooltip": "0.8× pitch — slowed + slightly lower."},
             {"id": "distort_8bit_game",  "icon": "👾", "label": "8-bit Game", "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("8bit_game"), "toggle": lambda: "8bit_game"  in audio_toggles.audio_distortions_active, "tooltip": "2-bit depth @ 8 kHz — retro video game bleeps."},
             {"id": "distort_robot",      "icon": "🤖", "label": "Robot",      "shortcut": True, "command": lambda: audio_toggles.toggle_audio_distortion("robot"),     "toggle": lambda: "robot"      in audio_toggles.audio_distortions_active, "tooltip": "Rapid micro-echoes + 30 Hz vibrato — robotic stutter."},
         ]},
        "---",
        {"id": "censors", "label": "Censors Toggle",
         "icon": lambda: f"({sum(1 for c in (censors.get_file_censors(state.playback.currently_playing.get('filename','')) or []) if not c.get('nsfw') and not c.get('mute') and not c.get('skip'))})",
         "button_label": "CENSORS",
         "shortcut": True, "command": censors.toggle_censor_bar,
         "toggle":  lambda: censors.censors_enabled,
         "tooltip": "Toggle regular censor bars on or off. NSFW censors have a separate toggle."},
        {"id": "censors_nsfw", "label": "NSFW Censors Toggle",
         "icon": lambda: f"({sum(1 for c in (censors.get_file_censors(state.playback.currently_playing.get('filename','')) or []) if c.get('nsfw'))})",
         "button_label": "NSFW CENS.",
         "shortcut": True, "command": censors.toggle_censor_nsfw_bar,
         "toggle":  lambda: censors.censors_nsfw_enabled,
         "tooltip": "Toggle NSFW censor bars on or off. Regular censors have a separate toggle."},
        {"id": "censor_editor", "icon": "➕", "label": "Censor Editor",
         "button_label": "CENSOR ED.",
         "command": lambda: censors.open_censor_editor(True),
         "tooltip": "Opens the censor editor to add, edit, or delete censor boxes for the current theme."},
        "---",
        {"id": "always_on_top", "icon": "📌", "label": "Always On Top",
         "button_label": "ON TOP",
         "command": autoplay_toggles.toggle_mpv_always_on_top,
         "toggle": lambda: state.controls.mpv_always_on_top,
         "tooltip": "Keep the mpv player window on top of all other windows."},
        {"id": "auto_refresh", "icon": "♻", "label": "Auto Refresh Metadata",
         "button_label": "AUTO REFRESH",
         "command": metadata_fetch.toggle_auto_auto_refresh,
         "toggle":  lambda: state.controls.auto_refresh_toggle,
         "tooltip": "Toggle auto refreshing jikan metadata (score, members) as themes play — never refreshes the same anime twice per session."},
        {"id": "fullscreen", "icon": "⛶", "label": "Fullscreen",
         "button_label": "FULLSCREEN",
         "command": autoplay_toggles.toggle_autoplay_fullscreen,
         "toggle": lambda: state.controls.autoplay_fullscreen,
         "tooltip": "Toggle whether the player starts in fullscreen when a track plays."},
        {"id": "progress_bar", "icon": "▬", "label": "Progress Bar",
         "button_label": "PROGRESS",
         "shortcut": True, "command": progress_bar_ops.toggle_progress_bar,
         "toggle":  lambda: state.controls.progress_bar_enabled,
         "tooltip": "Toggle a subtle progress bar overlay showing the current playback position."},
         "---",
        {"id": "enable_shortcuts", "icon": "", "label": "Enable Shortcuts",
         "button_label": "SHORTCUTS",
         "shortcut": True, "command": shortcut_dispatch.toggle_disable_shortcuts,
         "toggle":  lambda: not state.controls.disable_shortcuts,
         "tooltip": "Toggle shortcut keys on or off."},
        {"id": "view_shortcuts", "icon": "", "label": "Edit/View Shortcuts",
         "button_label": "VIEW KEYS",
         "shortcut": True, "command": shortcut_editor.open_shortcut_editor,
         "tooltip": "View and edit keyboard shortcuts."},
    ],

    # ── THEME ────────────────────────────────────────────────────────────────
    "theme": [
        {"label": "No theme loaded", "command": lambda: None,
         "condition": lambda: not state.playback.currently_playing.get("filename"),
         "tooltip": "No theme is currently playing."},
        {"id": "tag", "icon": "❌", "label": "Tag",
         "button_label": "TAG", "shortcut": True, "command": playlist_marks.tag,
         "condition": lambda: bool(state.playback.currently_playing.get("filename")),
         "toggle":  lambda: bool(playlist_marks.check_tagged(state.playback.currently_playing.get("filename"))),
         "tooltip": "Add or remove the current theme from the 'Tagged Themes' playlist."},
        {"id": "favorite", "icon": "❤", "label": "Favorite",
         "button_label": "FAVORITE", "shortcut": True, "command": playlist_marks.favorite,
         "condition": lambda: bool(state.playback.currently_playing.get("filename")),
         "toggle":  lambda: bool(playlist_marks.check_favorited(state.playback.currently_playing.get("filename"))),
         "tooltip": "Add or remove the current theme from the 'Favorite Themes' playlist."},
        {"id": "blind_mark", "icon": "👁", "label": "Blind Mark",
         "button_label": "BLIND MARK", "shortcut": True, "command": playlist_marks.blind_mark,
         "condition": lambda: bool(state.playback.currently_playing.get("filename")),
         "toggle":  lambda: bool(playlist_marks.check_blind_mark(state.playback.currently_playing.get("filename"))),
         "tooltip": "Add or remove the current theme from the 'Blind Themes' auto-round playlist."},
        {"id": "peek_mark", "icon": "👀", "label": "Reveal Mark",
         "button_label": "RV MARK", "shortcut": True, "command": playlist_marks.peek_mark,
         "condition": lambda: bool(state.playback.currently_playing.get("filename")),
         "toggle":  lambda: bool(playlist_marks.check_peek_mark(state.playback.currently_playing.get("filename"))),
         "tooltip": "Add or remove the current theme from the Reveal playlist (plays as a Reveal Round)."},
        {"id": "mute_peek_mark", "icon": "🔇", "label": "Mute Reveal Mark",
         "button_label": "MUTE RV MRK", "shortcut": True, "command": playlist_marks.mute_peek_mark,
         "condition": lambda: bool(state.playback.currently_playing.get("filename")),
         "toggle":  lambda: bool(playlist_marks.check_mute_peek_mark(state.playback.currently_playing.get("filename"))),
         "tooltip": "Add or remove the current theme from the Mute Reveal playlist (plays as a Mute Reveal Round)."},
        {"id": "add_to_playlist", "icon": "➕", "label": "Add to Playlist",
         "button_label": "ADD TO LIST", "command": playlist_marks.add_to_saved_playlist,
         "condition": lambda: bool(state.playback.currently_playing.get("filename")),
         "tooltip": "Add the current theme to one of your saved (non-system) playlists."},
        "---",
        {"id": "refetch_metadata", "icon": "📥", "label": "Fetch Theme Data",
         "button_label": "FETCH DATA", "command": metadata_fetch.refetch_metadata,
         "condition": lambda: bool(state.playback.currently_playing.get("filename")),
         "tooltip": "Fetch metadata for the currently playing theme from AnimeThemes, Jikan, AniList, and AniDB."},
        "---",
        {"id": "copy_filename", "icon": "⮺",  "label": "Copy Filename",
        "button_label": "COPY NAME", "command": lambda: pyperclip.copy(state.playback.currently_playing.get("filename", "")),
        "condition": lambda: bool(state.playback.currently_playing.get("filename")),
        "tooltip": "Copy the filename to the clipboard."},
        {"id": "download_theme", "icon": "⬇️", "label": "Download",
        "button_label": "DOWNLOAD", "command": menu_builder.download_current_theme,
        "condition": lambda: bool(state.playback.currently_playing.get("filename")) and menu_builder._cp_is_stream(),
              "tooltip": "Download or move this file to the local directory."},
        {"label": "File Actions", "icon": "📁",
         "condition": lambda: bool(state.playback.currently_playing.get("filename")) and not menu_builder._cp_is_stream(),
         "tooltip": "File operations for the currently playing theme.",
         "submenu": [
             {"id": "open_folder", "icon": "📁", "label": "Open Folder",
              "button_label": "OPEN FOLDER",  "command": lambda: media_ops.open_file_folder_by_filename(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: menu_builder._cp_is_local_file(),
              "tooltip": "Open the folder containing this file."},
             {"id": "cut_before", "icon": "✂️", "label": "Cut Before",
              "button_label": "CUT BEFORE", "command": lambda: media_ops.cut_before_current_time(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: ffmpeg_check.is_ffmpeg_available() and menu_builder._cp_is_local_file(),
              "tooltip": "Cut the file before the current playback position."},
             {"id": "cut_after", "icon": "✂️", "label": "Cut After",
              "button_label": "CUT AFTER", "command": lambda: media_ops.cut_after_current_time(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: ffmpeg_check.is_ffmpeg_available() and menu_builder._cp_is_local_file(),
              "tooltip": "Cut the file after the current playback position."},
             {"id": "rename_theme", "icon": "✏️", "label": "Rename",
              "button_label": "RENAME", "command": lambda: media_ops.rename_file_by_filename(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: menu_builder._cp_is_local_file(),
              "tooltip": "Rename the currently playing file."},
             {"id": "convert_theme", "icon": "🔄", "label": "Convert",
              "button_label": "CONVERT", "command": lambda: media_ops.convert_file_format_by_filename(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: ffmpeg_check.is_ffmpeg_available() and menu_builder._cp_is_local_file(),
              "tooltip": "Convert the file to a different format."},
             {"id": "edit_volume_theme","icon": "🔊", "label": "Edit Volume",
              "button_label": "EDIT VOL", "command": lambda: media_ops.edit_file_volume_by_filename(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: ffmpeg_check.is_ffmpeg_available() and menu_builder._cp_is_local_file(),
              "tooltip": "Adjust the audio volume of this file."},
             {"id": "delete_theme_file","icon": "❌", "label": "Delete File",
              "button_label": "DELETE FILE", "command": lambda: media_ops.delete_file_by_filename(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: menu_builder._cp_is_local_file(),
              "tooltip": "Permanently delete this file."},
         ]},
        {"label": "External Sites", "icon": "🔗",
         "condition": lambda: bool(state.playback.currently_playing.get("data")),
         "tooltip": "Open external database pages for this anime.",
         "submenu": [
             {"id": "open_igdb", "label": "IGDB",
              "button_label": "IGDB", "command": lambda: webbrowser.open(f"https://www.igdb.com/games/{(state.playback.currently_playing.get('data') or {}).get('igdb_slug') or (state.playback.currently_playing.get('data') or {}).get('igdb')}"),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("igdb")) and metadata_display.is_game(state.playback.currently_playing.get("data") or {}),
              "tooltip": "Open the IGDB page for this game."},
             {"id": "open_mal", "label": "MyAnimeList",
              "button_label": "MAL", "command": lambda: metadata_display.open_mal_page((state.playback.currently_playing.get("data") or {}).get("mal")),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("mal")) and not metadata_display.is_game(state.playback.currently_playing.get("data") or {}),
              "tooltip": "Open the MyAnimeList page for this anime."},
             {"id": "open_anidb", "label": "AniDB",
              "button_label": "ANIDB", "command": lambda: metadata_display.open_anidb_page((state.playback.currently_playing.get("data") or {}).get("anidb")),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("anidb")) and not metadata_display.is_game(state.playback.currently_playing.get("data") or {}),
              "tooltip": "Open the AniDB page for this anime."},
             {"id": "open_anilist", "label": "AniList",
              "button_label": "ANILIST", "command": lambda: metadata_display.open_anilist_page((state.playback.currently_playing.get("data") or {}).get("anilist")),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("anilist")) and not metadata_display.is_game(state.playback.currently_playing.get("data") or {}),
              "tooltip": "Open the AniList page for this anime."},
             {"id": "open_animethemes", "label": "AnimeThemes",
              "button_label": "ANIMETHEMES", "command": lambda: metadata_display.open_animethemes_anime_page((state.playback.currently_playing.get("data") or {}).get("animethemes_slug")),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("animethemes_slug")) and "[MAL]" not in state.playback.currently_playing.get("filename", "") and "[ID]" not in state.playback.currently_playing.get("filename", "") and state.playback.currently_playing.get("type") == "theme",
              "tooltip": "Open the AnimeThemes page for this anime."},
             {"id": "stream_animethemes", "icon": "▶", "label": "Stream on AnimeThemes",
              "button_label": "STREAM AT", "command": lambda: metadata_display.anime_themes_video(state.playback.currently_playing.get("filename", "")),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("animethemes_slug")) and "[MAL]" not in state.playback.currently_playing.get("filename", "") and "[ID]" not in state.playback.currently_playing.get("filename", "") and state.playback.currently_playing.get("type") == "theme",
              "tooltip": "Stream this theme on the AnimeThemes website."},
         ]},
        {"label": "Media", "icon": "🖼",
         "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("trailer") or (state.playback.currently_playing.get("data") or {}).get("cover") or (state.config.OPENAI_API_KEY and state.playback.currently_playing.get("data"))),
         "tooltip": "Cover art, trailer, and AI trivia for this anime.",
         "submenu": [
             {"id": "show_cover", "icon": "🖼",  "label": "Show Cover",
              "button_label": "COVER", "command": lambda: metadata_display.create_cover_popup(f"{metadata_display.get_display_title(state.playback.currently_playing.get('data') or {})} Cover", (state.playback.currently_playing.get('data') or {}).get('cover'))(),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("cover")),
              "tooltip": "Show the cover art for this anime."},
             {"id": "copy_cover_url", "icon": "⍘",   "label": "Copy Cover URL",
              "button_label": "COPY COVER", "command": lambda: pyperclip.copy((state.playback.currently_playing.get("data") or {}).get("cover", "")),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("cover")),
              "tooltip": "Copy the cover art URL to the clipboard."},
             {"id": "play_trailer", "icon": "▶",   "label": "Play Trailer",
              "button_label": "TRAILER", "command": streaming.play_trailer,
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("trailer")),
              "tooltip": "Play the trailer for this anime."},
             {"id": "copy_trailer_url",  "icon": "⍘",   "label": "Copy Trailer URL",
              "button_label": "COPY TRAILER", "command": lambda: pyperclip.copy((state.playback.currently_playing.get("data") or {}).get("trailer", "")),
              "condition": lambda: bool((state.playback.currently_playing.get("data") or {}).get("trailer")),
              "tooltip": "Copy the trailer URL to the clipboard."},
             {"id": "anime_trivia", "icon": "💡",  "label": "Trivia",
              "button_label": "TRIVIA", "command": lambda: trivia_round.generate_anime_trivia(state.playback.currently_playing.get("data"), True),
              "condition": lambda: bool(state.playback.currently_playing.get("data")) and bool(state.config.OPENAI_API_KEY),
              "tooltip": "Generate AI trivia about this anime. Prints in console."},
         ]},
    ],

    # ── HIDDEN (shortcuts only — no UI display) ─────────────────────────────
    "hidden": [
        {"id": "dock_player", "icon": "📌", "label": "Dock Player",
         "button_label": "DOCK", "shortcut": True, "command": dock_player_mod.dock_player,
         "tooltip": "Toggle docking the player to the bottom of the screen."},
        {"id": "search_themes",     "label": "Search Themes",
         "shortcut": True, "command": lambda: search_ops.search(add=state.metadata.playlist.get("infinite", False)),
         "tooltip": "Open the theme search (shortcut-key mode)."},
        {"id": "reroll_next", "icon": lambda: "🔄" if infinite.is_reroll_valid() else "", "label": "Re-roll Next Track",
         "button_label": lambda: "RE-ROLL" if infinite.is_reroll_valid() else "", "shortcut": True, "command": infinite.reroll_next,
         "tooltip": "Re-fetch the next track in infinite mode (only at the penultimate position)."},
        {"id": "cycle_light_mode",  "label": "Cycle Lightning Mode",
         "button_label": "CYCLE LIGHT", "shortcut": True, "command": shortcut_actions.cycle_light_mode,
         "tooltip": "Cycle through all lightning round modes in order."},
        {"id": "cycle_blind_peek",  "label": "Cycle Blind / Reveal",
         "button_label": "CYCLE BLIND/RV", "shortcut": True, "command": shortcut_actions.cycle_blind_peek,
         "tooltip": "Cycle: off → blind round → reveal round → mute reveal round."},
        {"id": "cycle_guess_stats", "label": "Cycle Stat Questions",
         "button_label": "CYCLE STAT ?s", "shortcut": True, "command": shortcut_actions.cycle_guess_stats,
         "tooltip": "Cycle bonus questions: year → score → popularity → members."},
        {"id": "cycle_guess_other", "label": "Cycle Other Questions",
         "button_label": "CYCLE OTHER ?s", "shortcut": True, "command": shortcut_actions.cycle_guess_other,
         "tooltip": "Cycle bonus questions: freeform → studio → song → artist."},
        # ── PLAYER CONTROLS (no toolbar button — popout / shortcuts only) ──
        {"id": "play_pause", "icon": "⏯",  "label": "Play/Pause",  "button_label": "PLAY/PAUSE",
         "shortcut": True, "command": transport.play_pause,  "tooltip": "Toggle play or pause."},
        {"id": "stop", "icon": "⏹", "label": "Stop", "button_label": "STOP",
         "shortcut": True, "command": transport.stop, "tooltip": "Stop playback."},
        {"id": "previous", "icon": "⏮", "label": "Previous","button_label": "PREVIOUS",
         "shortcut": True, "command": transport.play_previous, "tooltip": "Go to the previous theme."},
        {"id": "next", "icon": "⏭", "label": "Next","button_label": "NEXT",
         "shortcut": True, "command": transport.play_next, "tooltip": "Go to the next theme."},
        {"id": "skip_to_end", "icon": "⏭", "label": "Skip to End", "button_label": "SKIP TO END",
         "shortcut": True, "command": lambda: (transport.seek_to(state.widgets.player.get_length() - 3000), state.widgets.root.after(0, coming_up_ui.show_skip_to_end_osd)) if state.widgets.player.get_length() > 3000 else None,
         "tooltip": "Seek the current track to the last few seconds.",
         "submenu": [
             {"id": "skip_to_end_seek",    "icon": "⏭", "label": "Skip to End (Seek)",
              "shortcut": True,
              "command": lambda: (transport.seek_to(state.widgets.player.get_length() - 3000), state.widgets.root.after(0, coming_up_ui.show_skip_to_end_osd)) if state.widgets.player.get_length() > 3000 else None,
              "tooltip": "Instantly seek the current track to the last few seconds."},
             {"id": "skip_to_end_ff",      "icon": "⏩", "label": "Fast Forward to End",
              "shortcut": True,
              "command": lambda: coming_up_ui.fast_forward_to_end(4, 500) if state.widgets.player.get_length() > 3000 else None,
              "tooltip": "Play at 4× speed for 0.5 s then seek to the last few seconds."},
             {"id": "skip_to_end_ff_slow", "icon": "⏩", "label": "Fast Forward to End (slow)",
              "shortcut": True,
              "command": lambda: coming_up_ui.fast_forward_to_end(4, 2000) if state.widgets.player.get_length() > 3000 else None,
              "tooltip": "Play at 4× speed for 2 s then seek to the last few seconds."},
         ]},
        {"id": "lightning_start", "label": "Start/Stop Lightning",
         "button_label": lambda: "⏹ STOP" if state.lightning.light_mode else "▶ START",
         "shortcut": True, "command": lightning_manager.select_lightning_mode,
         "toggle":  lambda: bool(state.lightning.light_mode),
         "tooltip": "Start or stop the currently selected lightning round mode."},
        {"id": "close_list", "label": "Close List",
         "button_label": "CLOSE LIST", "shortcut": True, "command": lambda: lists._close_list(state.widgets.right_column),
         "tooltip": "Close the currently open list or panel in the right column."},
    ],

    # ── BUTTON RIGHT-CLICK ACTIONS ────────────────────────────────────────────
    # Maps section name → callable invoked when the toolbar button is right-clicked.
    # Add an entry here to attach a shortcut action to a button's right-click.
    "_right_click": {
        # Each entry: (action, label_func) — label_func called *after* action so it reflects new state
        #file open settings
        "file": (lambda: settings_popup.show_settings_popup(), lambda: "CONFIG"),
        "playlist" : (lambda: lists.show_playlist(), lambda: "SHOW PLAYLIST" if state.lists.list_loaded == "playlist" else "HIDE PLAYLIST"),
        "queue": (lambda: lightning_manager.toggle_light_mode("variety"), lambda: "VARIETY UP NEXT" if state.lightning.light_mode == "variety" else "VARIETY DISABLED"),
        "bonus":   (lambda: bonus.guess_extra("multiple"), lambda: "MULTIPLE CHOICE"),
        "information": (information_popup.toggle_info_popup, lambda: "INFO POPUP"),
        "theme": (lambda: playlist_marks.tag() if bool(state.playback.currently_playing.get("filename")) else None, lambda: ("TAG ON" if bool(playlist_marks.check_tagged(state.playback.currently_playing.get("filename"))) else "TAG OFF") if bool(state.playback.currently_playing.get("filename")) else None),
        "toggles": (shortcut_dispatch.toggle_disable_shortcuts,
                    lambda: "KEYS ON" if not state.controls.disable_shortcuts else "KEYS OFF"),
        "popout": (lambda: popout_window.create_popout_controls(), lambda: "POPOUT OPEN"),
        "directory": (lambda: censors.toggle_censor_bar(), lambda: "CENSORS ON" if censors.censors_enabled else "CENSORS OFF"),
    },

    }  # end _get_menu_registry()
